apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jfkla3pwj-go 
  janus-idp.io/tekton: jfkla3pwj-go
  backstage.io/kubernetes-id: jfkla3pwj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jfkla3pwj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml