apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jfkla3pwj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jfkla3pwj-go 
  name: jfkla3pwj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jfkla3pwj-go 
